# dein
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

# File unitilities
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''    
    nnoremap <C-t> :NERDTreeToggle<CR>
    nnoremap <leader>n :NERDTreeFocus<CR>
    let g:NERDTreeShowHidden=1
    let g:NERDTreeShowBookmarks=1
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

# Color Theme
[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
    colorscheme nord
    syntax on
'''

# Dev unitilities
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

[[plugins]]
repo = 'airblade/vim-gitgutter'
