[[plugins]]
repo = 'ElmCast/elm-vim'
on_ft = ['elm']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
hook_source = '''
    let g:syntastic_rust_checkers = ['cargo', 'rustc']
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

[[plugins]]
repo = 'thosakwe/vim-flutter'
on_ft = ['dart']
hook_post_source = '''
call FlutterMenu()
'''
