[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''    
    nnoremap <C-t> :NERDTreeToggle<CR>
    let g:NERDTreeShowHidden=1
    let g:NERDTreeShowBookmarks=1
'''

[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
    colorscheme nord
    syntax on
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
