SCRIPT_DIR=$(cd $(dirname $0) && pwd)
VSCODE_DOT_DIRECTORY=$HOME/.vscode
VSCODE_SETTING_DIR=$HOME/Library/Application\ Support/Code/User
VSCODE_SETTING_FILE=settings.json

ln -s "$SCRIPT_DIR/$VSCODE_SETTING_FILE" "$VSCODE_DOT_DIRECTORY/$VSCODE_SETTING_FILE"

rm "$VSCODE_SETTING_DIR/$VSCODE_SETTING_FILE"
ln -s "$VSCODE_DOT_DIRECTORY/$VSCODE_SETTING_FILE" "$VSCODE_SETTING_DIR/$VSCODE_SETTING_FILE"

$SCRIPT_DIR/install-extensions.sh
