name: Test Init

on: [push]

jobs:
  build:

    runs-on: [macos-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Cache brew dependencies (download)
      uses: actions/cache@v4.2.2
      env:
        cache-name: cache-brew-dependencies
      with:
        path: ~/Library/Caches/Homebrew
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/.Brewfile') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Test make all
      run: make all
